/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Fibonacci {
    public int calculate(int number) {
        if(number == 0) {
            return 0;
        } if(number <= 2) {
            return 1;
        }
        
        return 2;
    }
}
