/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Fibonacci {
    public int calculate(int number) {
        if(number <= 1) return number;
        
        return calculate(number - 1) + calculate(number - 2);
    }
}
